output: docs
clean: true
skip_undocumented: true
sdk: iphone
swift_version: 4.0.2
module_version: 0.0.53
xcodebuild_arguments: [clean,build,-project,_Pods.xcodeproj,-scheme,StanwoodCore]
source_directory: StanwoodCore/Classes
author: Tal Zion
author_url: tal.zion@stanwood.io
copyright: 2018 Stanwood GmbH
readme: README.md
podspec: StanwoodCore.podspec
github_url: https://github.com/stanwood/Stanwood_Core
min_acl: public
theme: fullwidth
