# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

os: osx
osx_image: xcode10.2
branches:
  only:
    - testRun
before_install:
  - gem install cocoapods # Since Travis is not always on latest version
  - pod install
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - pod lib lint
after_success:
  - 'echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.s